### ISSUE TITLE
invalid character 'D' looking for beginning of value

### ISSUE THREAD

**Issue by RagaviAmutha** [answear/kube-vcloud-flexvolume#13]
While trying to launch pod using the provided nginx.yaml(https://github.com/sysoperator/kube-vcloud-flexvolume/blob/master/examples/nginx.yaml) in your repository, the following error has occurred in kubelet service log.

**During attach the disk, there is an error:**
Operation for "\"flexvolume-sysoperator.pl/vcloud/testdisk33\"" failed. No retries permitted until 2018-11-13 11:39:19.84658885 +0000 UTC m=+7370.033281972 (durationBeforeRetry 2m2s). Error: "AttachVolume.Attach failed for volume \"testdisk33\" (UniqueName: \"flexvolume-sysoperator.pl/vcloud/testdisk33\") from node \"k8s-env34-cert-new-o101devorg-1238778\" : invalid character 'D' looking for beginning of value"

I have attached the result of attach method call ( Response in detail along with this)
[attachcallresponsethroughyaml.txt](https://github.com/sysoperator/kube-vcloud-flexvolume/files/2576533/attachcallresponsethroughyaml.txt)

**Comment by dzolnierz** [comment]
Looks like you are getting debug from pyvcloud on STDOUT instead of being written to file /var/log/pyvcloud.log. The "attach" operation finished successfully. There is:

```
{"status": "Success", "device": "/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:3:0-part1"}
```
message at the end of attached file.

Which version of pyvcloud are you using? Could you post driver configuration (/opt/vcloud-flexvolume/etc/config.yaml) here? (Please remove any credentials before.)

**Comment by RagaviAmutha** [comment]
pyvcloud - 19.3.0(version)

(/opt/vcloud-flexvolume/etc/config.yaml)
vcloud:
  host: <HOST without proto>
  org: <ORG>
  vdc: <VDC NAME>
  username: <USERNAME>
  password: <PASSWORD>
  verify_ssl_certs: False
  log: True
  log_file: /var/log/pyvcloud.log
  api_version: '27.0'
  default_storage: VC7-SSD
  etcd:
    host: <worker-node-name>(eg.k8s-node)
    port: 2379
    # You can left below fields empty to not using TLS
    ca_cert: /root/ca.crt
    cert: /root/kubernetes.crt
    key: /root/kubernetes-key.key
    timeout: 5
  debug: False
