### ISSUE TITLE
kube-vcloud CSI plugin?

### ISSUE THREAD

**Issue by pasikarkkainen** [answear/kube-vcloud-flexvolume#14]
Hello! Are there currently plans to migrate kube-vcloud-flexvolume to CSI plugin model, which seems to be the recommended way in current Kubernetes versions for deploying storage plugins/drivers.

And thanks a lot for working on this project, it's an important feature to have :)

**Comment by dzolnierz** [comment]
The moment we needed this driver, CSI was in the alpha version. Hence the use of FlexVolume. Due to the maturity of the current solution, we do not have plans to rewrite the driver at the moment.

**Comment by dzolnierz** [comment]
The 2.4.0 release introduces external provisioner implementing concept described [here](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/volume-provisioning.md). I think it's a good compromise between lack of a CSI plugin and creating PVs for Pods manually like before.
